### PR TITLE
Fixes #217

### LINKED ISSUE #217: NoMethodError in Course Explorer feature
For an example traceback, see [this build](https://travis-ci.org/hacsoc/the_jolly_advisor/builds/133915784#L482-L488).

### PR DESCRIPTION
**Pull request by ajm188**
The issues were:
1. `course_data` contained a space, so the indexing was off for the course num
2. Change `course_instance` to `course_instances`, since courses have many
3. Courses have many professors, so we need to check if *any* professor
   matches the search.

### CODE REVIEW

File: features/step_definitions/course_explorer_steps.rb [hunk 1]
```diff
@@ -21,12 +21,12 @@
...
-    professor = Course.includes(course_instance: :professor)
-                      .find_by(department: dept, course_number: num)
-                      .professor
-    expect(professor.name).to start_with(@professor.name)
+    dept, num = course_data.split ' '
+    professors = Course.includes(course_instances: :professor)
+                       .find_by(department: dept, course_number: num)
+                       .professors
+    names = professors.map(&:name)
+    expect(names.any? {|name| name.start_with?(@professor.name)}).to be true
```
Comment (ajm188) [inline features/step_definitions/course_explorer_steps.rb]: Also if anyone knows a more "rspec-y" way to express this, let me know

Comment (ajm188) [inline features/step_definitions/course_explorer_steps.rb]: Ooh found it; new commit coming right up

**Comment by StephHippo** [comment]
👍 That code coverage increase.
